services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    ports:
      - 6789:5678
    environment:
      TZ: "Asia/Manila"
      GENERIC_TIMEZONE: "Asia/Manila"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES: "false"
      N8N_TRUSTPROXY: "true"
      N8N_PROXY_HOPS: "1"
      EDITOR_BASE_URL: ${NGROK_URL}
      WEBHOOK_URL: ${NGROK_URL}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./data:/home/node/.n8n-files/files/:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pldt_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - backend_db:/app/db
      - backend_audio:/app/audio
    restart: unless-stopped
    depends_on:
      - n8n

  chatbot:
    build:
      context: ./ChatBotApp
      dockerfile: Dockerfile
    container_name: chatbot
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  n8n_data:
  backend_db:
  backend_audio:    # ← add this